### ISSUE TITLE
[feature request] isa string in url

### ISSUE THREAD

**Issue by nibrunieAtSi5** [drom/rv#23] opened 2023-03-11 07:16 UTC
It would be very useful if the default ISA string on opening could be initialized from the url, for example: `rv.drom.io/rva23u64` would open the description of the RVA23 user-mode 64-bit profile. That way people could exchange url when describing an ISA string and easily access the description without having to enter it in the web interface.

This feature could also be used to share a URL once an ISA string has been entered.

I apologize if this feature is already implemented and I did not figure out how to use it.

**Comment by drom** [comment] 2023-03-15 18:17
It works with addition of `?` sign
[rv.drom.io/?rva23u64](https://rv.drom.io/?rva23u64)

**Comment by drom** [comment] 2023-03-15 18:46
duplicate of #2

**Closed as completed by drom** 2023-03-15 18:46 UTC
